// The 16 forced-choice trait-axis pairs, embedded directly rather than
// fetched from a Google Sheet — no external dependency to misconfigure for
// something this small and rarely edited. To change wording, edit this file
// and redeploy.
export const TRAIT_AXIS_ITEMS = [
  {
    pair_id: 'TA1',
    axis: 1,
    axis_name: 'Conceptual vs Concrete',
    statement_a: "I'm energized by open-ended questions with no clear answer yet.",
    statement_b: "I'm energized by well-defined problems with a right answer to find.",
    a_pole: 'Conceptual',
    b_pole: 'Concrete',
  },
  {
    pair_id: 'TA2',
    axis: 1,
    axis_name: 'Conceptual vs Concrete',
    statement_a: "I'd rather explore three possibilities than commit early to one.",
    statement_b: "I'd rather commit early and refine through iteration on the details.",
    a_pole: 'Conceptual',
    b_pole: 'Concrete',
  },
  {
    pair_id: 'TA3',
    axis: 1,
    axis_name: 'Conceptual vs Concrete',
    statement_a: 'I think in terms of what this could become.',
    statement_b: 'I think in terms of how this actually gets built.',
    a_pole: 'Conceptual',
    b_pole: 'Concrete',
  },
  {
    pair_id: 'TA4',
    axis: 1,
    axis_name: 'Conceptual vs Concrete',
    statement_a: "I'm comfortable when a project's direction is still fuzzy.",
    statement_b: 'I want clarity and a defined path before I feel comfortable moving.',
    a_pole: 'Conceptual',
    b_pole: 'Concrete',
  },
  {
    pair_id: 'TA5',
    axis: 1,
    axis_name: 'Conceptual vs Concrete',
    statement_a: 'I trust my instinct about what will feel right.',
    statement_b: 'I trust what can be verified measured or proven.',
    a_pole: 'Conceptual',
    b_pole: 'Concrete',
  },
  {
    pair_id: 'TA6',
    axis: 1,
    axis_name: 'Conceptual vs Concrete',
    statement_a: 'I get more satisfaction from an original idea than from flawless execution.',
    statement_b: 'I get more satisfaction from flawless execution than from the original idea.',
    a_pole: 'Conceptual',
    b_pole: 'Concrete',
  },
  {
    pair_id: 'TA7',
    axis: 1,
    axis_name: 'Conceptual vs Concrete',
    statement_a: 'I ask why are we doing it this way more than how do we do it.',
    statement_b: 'I ask how do we do it more than why are we doing it this way.',
    a_pole: 'Conceptual',
    b_pole: 'Concrete',
  },
  {
    pair_id: 'TA8',
    axis: 1,
    axis_name: 'Conceptual vs Concrete',
    statement_a: "I'm drawn to precedent and inspiration outside of the immediate problem.",
    statement_b: "I'm drawn to the immediate technical constraints of the problem itself.",
    a_pole: 'Conceptual',
    b_pole: 'Concrete',
  },
  {
    pair_id: 'TA9',
    axis: 2,
    axis_name: 'Content vs People',
    statement_a: "I'd rather be the one producing the work than the one coordinating who does it.",
    statement_b: "I'd rather coordinate the team than personally produce the work.",
    a_pole: 'Content',
    b_pole: 'People',
  },
  {
    pair_id: 'TA10',
    axis: 2,
    axis_name: 'Content vs People',
    statement_a: 'My attention naturally goes to the quality of the output.',
    statement_b: 'My attention naturally goes to whether the people and schedule are aligned.',
    a_pole: 'Content',
    b_pole: 'People',
  },
  {
    pair_id: 'TA11',
    axis: 2,
    axis_name: 'Content vs People',
    statement_a: "I feel most useful when I'm heads-down solving a problem.",
    statement_b: "I feel most useful when I'm keeping a group of people moving together.",
    a_pole: 'Content',
    b_pole: 'People',
  },
  {
    pair_id: 'TA12',
    axis: 2,
    axis_name: 'Content vs People',
    statement_a: 'A good day is one where I made real progress on the work itself.',
    statement_b: 'A good day is one where I kept everything and everyone on track.',
    a_pole: 'Content',
    b_pole: 'People',
  },
  {
    pair_id: 'TA13',
    axis: 2,
    axis_name: 'Content vs People',
    statement_a: "I'd rather be an expert others come to for answers.",
    statement_b: "I'd rather be the person others come to for direction and decisions.",
    a_pole: 'Content',
    b_pole: 'People',
  },
  {
    pair_id: 'TA14',
    axis: 2,
    axis_name: 'Content vs People',
    statement_a: 'I notice the technical or design quality of a project first.',
    statement_b: 'I notice the team dynamics and communication of a project first.',
    a_pole: 'Content',
    b_pole: 'People',
  },
  {
    pair_id: 'TA15',
    axis: 2,
    axis_name: 'Content vs People',
    statement_a: "I'm energized by mastering the content of my work.",
    statement_b: "I'm energized by orchestrating people time and resources.",
    a_pole: 'Content',
    b_pole: 'People',
  },
  {
    pair_id: 'TA16',
    axis: 2,
    axis_name: 'Content vs People',
    statement_a: "I'd rather have deep ownership over one piece of the work.",
    statement_b: "I'd rather have broad visibility across the whole project.",
    a_pole: 'Content',
    b_pole: 'People',
  },
];
